# Following
# https://github.com/SUSE/style-guides/blob/master/Ruby.md

Metrics/BlockLenght:
  Exclude: 'spec/**/*'

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Is there any justification for "aligned" which is the default?
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#arrays
Style/WordArray:
  Enabled: false

# align arrows:
# "foo"     => true
# "foo_bar" => false
# and also colons:
# foo:     true
# foo_bar: false
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# no extra indentation for multiline function calls
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# no extra indentation for case
Style/CaseIndentation:
  EnforcedStyle: end

# "unless" has a different connotation than "if not"
Style/NegatedIf:
  Enabled: false

# use "raise" instead of "fail"
Style/SignalException:
  EnforcedStyle: only_raise

# do not force %r
Style/RegexpLiteral:
  Enabled: false

# Easier recognization if access modified used
Style/AccessModifierIndentation:
  EnforcedStyle: outdent

# method_alias is safer and more predictable
Style/Alias:
  EnforcedStyle: prefer_alias_method
